### ISSUE TITLE
LDTP linux cross-compiler build steps 

### ISSUE THREAD

**Issue by brownie313** [ldtp/ldtp2#38]
Hi All,

I need to build ldtp using a specific cross compiler so it can run on my linux build. 
Has anyone had any luck with this? Any pointers on how to go about this task would be highly appreciated.

Thanks a lot in advance.

**Comment by richelbilderbeek** [comment]
I know how to cross-compile from GNU/Linux to Windows ([see my MXE tutorial](https://github.com/richelbilderbeek/mxe_tutorial)). I do that because I find it unnecessary to buy Windows for myself.

When cross-compiling from [what?] to GNU/Linux, it is my experience it to be way easier to just install and compile in the target environment. Setting up a cross-compile toolchain is harder. If you dare to set up such a toolchain, I'd be happy to follow that, but I cannot help you and I will try hard never do so myself.

I do think this GitHub is not the best place to ask for help about setting up a cross-compiler toolchain. 

I hope this is of some help.

Good luck, Richel

**Comment by brownie313** [comment]
Dear Richel,

Thanks for the quick response. Luckily, I  already have the toolchain for
the embedded Linux OS that I want to cross compile LDTP for.

It's an embedded system so compiling on the target is not an option due to
limited resources. I only have access to push a compiled binary or library
file onto the target system and then execute it.

I suppose our work will be easier now. On the road bow. Will look at your
tutorial later.

Thanks again,
Brownson

On May 12, 2017 17:38, "Richel Bilderbeek" <notifications@github.com> wrote:

I know how to cross-compile from GNU/Linux to Windows (see my MXE tutorial
<https://github.com/richelbilderbeek/mxe_tutorial>). I do that because I
find it unnecessary to buy Windows for myself.

When cross-compiling from [what?] to GNU/Linux, it is my experience it to
be way easier to just install and compile in the target environment.
Setting up a cross-compile toolchain is harder. If you dare to set up such
a toolchain, I'd be happy to follow that, but I cannot help you and I will
try hard never do so myself.

I do think this GitHub is not the best place to ask for help about setting
up a cross-compiler toolchain.

I hope this is of some help.

Good luck, Richel

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ldtp/ldtp2/issues/38#issuecomment-301018900>, or mute
the thread

**Comment by richelbilderbeek** [comment]
Ah, clear. Too bad I have no experience with that. Good luck!

**Comment by richelbilderbeek** [comment]
I guess this Issue can be closed :+1:
